---
#
# Ansible managed
#
repository:
  description: Install Hashicorp Vault, either a package or a binary.
  homepage: https://robertdebock.nl/
  topics: vault, hashicorp, ansible, molecule, tox, playbook, hacktoberfest
