---
- name: test if vault_version is set correctly
  assert:
    that:
      - vault_version is defined
    quiet: yes

- name: test if vault_storages is set correctly
  assert:
    that:
      - vault_storages is defined
      - vault_storages is iterable
    quiet: yes

- name: test if item in vault_storages is set correctly
  assert:
    that:
      - item.name is defined
      - item.name in [ "raft" ]
      - item.path is defined
      - item.node_id is defined
    quiet: yes
  loop: "{{ vault_storages }}"
  loop_control:
    label: "{{ item.name }}"

- name: test if item in vault_listeners is set correctly
  assert:
    that:
      - item.name is defined
      - item.name in [ "tcp" ]
      - item.address is defined
      - item.tls_disable is defined
      - item.tls_disable in [ "0", "1" ]
    quiet: yes
  loop: "{{ vault_listeners }}"
  loop_control:
    label: "{{ item.name }}"

- name: test if vault_api_addr is set correctly
  assert:
    that:
      - vault_api_addr is defined
    quiet: yes

- name: test if vault_cluster_addr is set correctly
  assert:
    that:
      - vault_cluster_addr is defined
    quiet: yes

- name: test if vault_ui is set correctly
  assert:
    that:
      - vault_ui is defined
      - vault_ui is boolean
    quiet: yes

- name: test if vault_key_shares is set correctly
  assert:
    that:
      - vault_key_shares is defined
      - vault_key_shares is number
      - vault_key_shares > 0
    quiet: yes

- name: test if vault_key_threshold is set correctly
  assert:
    that:
      - vault_key_threshold is defined
      - vault_key_threshold is number
      - vault_key_threshold > 0
    quiet: yes

- name: test if vault_key_shares and vault_key_threshold are set correctly
  assert:
    that:
      - vault_key_threshold <= vault_key_shares
    quiet: yes

- name: test if vault_unseal_keys is set correctly
  assert:
    that:
      - vault_unseal_keys | length >= vault_key_threshold
      - vault_unseal_keys is iterable
    quiet: yes
  when:
    - vault_unseal_keys is defined
