---

- name: test if vault_disable_clustering is set correctly
  assert:
    that:
      - vault_disable_clustering is defined
      - vault_disable_clustering is string
      - vault_disable_clustering in [ "false", "true" ]
    quiet: yes

- name: test if vault_cluster_addr is set correctly
  assert:
    that:
      - vault_cluster_addr is defined
      - vault_cluster_addr is string
    quiet: yes
  when:
    - vault_disable_clustering == "false"

- name: test if vault_api_addr is set correctly
  assert:
    that:
      - vault_api_addr is defined
      - vault_api_addr is string
    quiet: yes

- name: test if vault_plugin_directory is set correctly
  assert:
    that:
      - vault_plugin_directory is defined
      - vault_plugin_directory is string
    quiet: yes

- name: test if vault_storages is set correctly
  assert:
    that:
      - vault_storages is defined
      - vault_storages is iterable
    quiet: yes

- name: test if item in vault_storages is set correctly
  assert:
    that:
      - item.name is defined
      - item.name is string
      - item.name in [ "raft" ]
      - item.path is defined
      - item.path is string
      - item.node_id is defined
      - item.node_id is string
    quiet: yes
  loop: "{{ vault_storages }}"
  loop_control:
    label: "{{ item.name }}"

- name: test if vault_listeners is set correctly
  assert:
    that:
      - vault_listeners is defined
      - vault_listeners is iterable
    quiet: yes

- name: test if item in vault_listeners is set correctly
  assert:
    that:
      - item.name is defined
      - item.name is string
      - item.name in [ "tcp" ]
      - item.address is defined
      - item.address is string
      - item.cluster_address is defined
      - item.cluster_address is string
      - item.tls_disable is defined
      - item.tls_disable is string
      - item.tls_disable in [ "false", "true" ]
    quiet: yes
  loop: "{{ vault_listeners }}"
  loop_control:
    label: "{{ item.name }}"

- name: test if vault_ui is set correctly
  assert:
    that:
      - vault_ui is defined
      - vault_ui is string
      - vault_ui in [ "false", "true" ]
    quiet: yes

- name: test if vault_key_shares is set correctly
  assert:
    that:
      - vault_key_shares is defined
      - vault_key_shares is number
      - vault_key_shares > 0
    quiet: yes

- name: test if vault_key_threshold is set correctly
  assert:
    that:
      - vault_key_threshold is defined
      - vault_key_threshold is number
      - vault_key_threshold > 0
    quiet: yes

- name: test if vault_key_shares and vault_key_threshold are set correctly
  assert:
    that:
      - vault_key_threshold <= vault_key_shares
    quiet: yes

- name: test if vault_show_unseal_information is set correctly
  assert:
    that:
      - vault_show_unseal_information is defined
      - vault_show_unseal_information is boolean

- name: test if vault_unseal_keys is set correctly
  assert:
    that:
      - vault_unseal_keys | length >= vault_key_threshold
      - vault_unseal_keys is iterable
    quiet: yes
  when:
    - vault_unseal_keys is defined

- name: test if vault_disable_mlock is set correctly
  assert:
    that:
      - vault_disable_mlock is defined
      - vault_disable_mlock is string
      - vault_disable_mlock in [ "false", "true" ]
    quiet: yes
