---
- name: start vault follower
  service:
    name: vault
    state: started
    enabled: true

# TODO: join follower to leader is not idempotent.
- name: join follower to leader
  command: vault operator raft join -tls-skip-verify http://{{ vault_leader }}:8200
  changed_when: no
  register: vault_join_member_to_leader
  until:
    - vault_join_member_to_leader is succeeded
  retries: 5
  environment:
    VAULT_ADDR: "{{ vault_api_addr }}"

# TODO: unseal vault follower is not idempotent.
- name: unseal vault follower
  command: vault operator unseal {{ item }}
  changed_when: no
  environment:
    VAULT_ADDR: "{{ vault_api_addr }}"
  loop: "{{ vault_init_output.unseal_keys_b64 }}"
  loop_control:
    label: "hidden"
  no_log: yes

- name: restart vault followers
  service:
    name: vault
    state: restarted
    enabled: true
