---
- name: check status of vault follower
  command: vault status -format=yaml
  environment:
    VAULT_ADDR: "{{ vault_api_addr }}"
  register: vault_status_raw
  changed_when: no
  check_mode: no
  failed_when:
    - vault_status_raw.rc == 1

- name: save vault_status for follower
  set_fact:
    vault_status: "{{ vault_status_raw.stdout | from_yaml }}"

- name: configure follower
  block:
    - name: join follower to leader
      command: vault operator raft join -tls-skip-verify http://{{ vault_leader }}:8200
      changed_when: no
      register: vault_join_member_to_leader
      until:
        - vault_join_member_to_leader is succeeded
      retries: 5
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"

    - name: unseal vault follower
      command: vault operator unseal {{ item }}
      changed_when: no
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
      loop: "{{ vault_init_output.unseal_keys_b64 }}"
      loop_control:
        label: "hidden"
      no_log: yes
  when:
    - vault_status.sealed | bool
