---
- name: start vault follower
  service:
    name: vault
    state: started
    enabled: true

- name: join member to leader
  command: vault operator raft join -tls-skip-verify http://{{ vault_leader }}:8200
  register: vault_join_member_to_leader
  until:
    - vault_join_member_to_leader is succeeded
  retries: 5
  environment:
    VAULT_ADDR: "{{ vault_api_addr }}"
  args:
    creates: nothing

- name: restart vault followers
  service:
    name: vault
    state: restarted
    enabled: true
