---
- name: start vault follower
  service:
    name: vault
    state: started
    enabled: true

- name: join member to leader
  command: vault operator raft join -tls-skip-verify http://{{ vault_leader }}:8200
  environment:
    VAULT_ADDR: "{{ vault_api_addr }}"
  args:
    creates: nothing

- name: restart vault followers
  service:
    name: vault
    state: restarted
    enabled: true
