---

- name: Disable swap
  when:
    - vault_hardening_disable_swap
  block:
    - name: Disable swap now
      ansible.builtin.command:
        cmd: swapoff -a
      when:
        - ansible_swaptotal_mb > 0

    - name: Disable swap permanently
      ansible.builtin.mount:
        name: swap
        state: absent

- name: Disable core dumps
  community.general.pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop:
    - domain: '*'
      limit_type: hard
      limit_item: core
      value: 0
    - domain: '*'
      limit_type: soft
      limit_item: core
      value: 0
  loop_control:
    label: "{{ item.limit_item }}"
  when:
    - vault_hardening_disable_core_dumps

- name: Disable Shell Command History
  ansible.builtin.copy:
    dest: /etc/profile.d/vault.sh
    content: |
      export HISTIGNORE="&:vault*"
    mode: '0644'
    owner: root
    group: root
  when:
    - vault_hardening_disable_shell_command_history

- name: Configure SELinux / AppArmor
  when:
    - vault_hardening_configure_selinux_apparmor
  block:
    - name: Enable SELinux
      when:
        - ansible_selinux.status == "enabled"
      block:
        - name: Install selinux-policy
          ansible.builtin.package:
            name: selinux-policy
            state: present

        - name: Set SELinux policy
          ansible.builtin.selinux:
            policy: targeted
            state: enforcing

    - name: Enable AppArmor (enforcing)
      ansible.builtin.command:
        cmd: aa-enforce /etc/apparmor.d/usr.bin.vault
      when:
        - ansible_apparmor.status == "enabled"
