---
- name: configure leader
  block:
    - name: initialize vault on leader
      command: vault operator init -key-shares={{ vault_key_shares }} -key-threshold={{ vault_key_threshold }} -format=yaml
      register: vault_operator_init
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
      when:
        - not vault_status.initialized | bool

    - name: save vault_init_output for leader
      set_fact:
        vault_init_output: "{{ vault_operator_init.stdout | from_yaml }}"
      when:
        - vault_operator_init is defined
        - vault_operator_init.stdout is defined

    - name: unseal vault leader
      block:
        - name: show unseal information
          block:
            - name: show unseal keys for leader
              debug:
                msg: "{{ vault_init_output.unseal_keys_b64 | default(vault_unseal_keys) }}"

            - name: show root token for leader
              debug:
                msg: "{{ vault_init_output.root_token | default(vault_root_token) }}"
              when:
                - vault_init_output is defined and
                  vault_init_output.root_token is defined or
                  vault_root_token is defined
          when:
            - vault_show_unseal_information | bool

        - name: unseal vault leader
          command: vault operator unseal {{ item }}
          environment:
            VAULT_ADDR: "{{ vault_api_addr }}"
          loop: "{{ vault_init_output.unseal_keys_b64 | default(vault_unseal_keys) }}"
          loop_control:
            label: "hidden"
          no_log: yes
          when:
            - vault_status.sealed | bool
      when:
        - (vault_init_output is defined and
          vault_init_output.unseal_keys_b64 is defined and
          vault_init_output.unseal_keys_b64 is iterable) or
          (vault_unseal_keys is defined)
  run_once: yes

- name: backup vault
  block:
    - name: make a snapshot
      uri:
        url: "{{ vault_api_addr }}/v1/sys/storage/raft/snapshot"
        return_content: yes
        headers:
          X-Vault-Token: "{{ vault_init_output.root_token | default(vault_root_token) }}"
      register: vault_snapshot
      until:
        - vault_snapshot is succeeded
      retries: 10

    - name: save snapshot
      copy:
        dest: /root/raft.snap
        content: "{{ vault_snapshot.content }}"
        owner: root
        group: root
        mode: "0400"
  when:
    - vault_make_backup | bool
    - vault_init_output is defined and
      vault_init_output.root_token is defined or
      vault_root_token is defined
