---
# tasks file for vault

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Include installation method specific tasks
  ansible.builtin.include_tasks:
    file: "{{ vault_installation_method }}.yml"

- name: Start vault
  ansible.builtin.service:
    name: vault
    state: started
    enabled: yes
