---
# tasks file for vault

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: run shared tasks
  include_tasks: shared.yml

- name: run leader tasks
  include_tasks: leader.yml

- name: run follower tasks
  include_tasks: follower.yml
  when:
    - not ansible_check_mode | bool
    - inventory_hostname != vault_leader
