---
# tasks file for vault

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install prerequisites
  ansible.builtin.package:
    name: "{{ vault_prerequisites }}"

- name: Include installation method specific tasks
  ansible.builtin.include_tasks:
    file: "{{ vault_installation_method }}.yml"

- name: Place Vault license
  ansible.builtin.copy:
    path: "{{ vault_path }}/etc/vault.d/license.hclic"
    content: "{{ vault_license }}"
  when:
    - vault_license is defined

- name: Start and enable vault
  ansible.builtin.service:
    name: vault
    state: started
    enabled: yes
