---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: try vault --version
      command: vault --version

    - name: connect to ui
      uri:
        url: "http://127.0.0.1:8200/ui/vault/auth?with=token"
